---
title: "Azure Cosmos DB Tutorial Using R"
author: Erik Howard
date: "Created: 2018-03-13; Last updated:`r Sys.Date()`"
output:
  html_document:
    toc: yes
    theme: cosmo
    highlight: tango
    number_sections: false
    code_folding: show
    fig_width: 10
    fig_height: 6
    fig_caption: true
---
```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, include=FALSE}
library(dplyr)
library(here)
library(mongolite)
```

```{r import_data}
launch_df <- read.csv(here("input", "spacex_launch_data.csv"), stringsAsFactors=FALSE)
glimpse(launch_df)
```

```{r cosmos_db_connect}
mgo <- mongo(db = "demo", collection = "launch",  url="[PRIMARY CONNECTION STRING]")
```

```{r insert_data}
mgo$info()
mgo$insert(launch_df)
```

```{r count}
mgo$count()
```

```{r find_all}
all <- mgo$find('{}')
head(all)
```

```{r find_with_limit}
limit <- mgo$find(limit=3)
print(limit)
```

```{r find_leo}
gto <- mgo$find('{"Orbit": "GTO"}')
print(gto)
```

```{r failed_landings}
fail <- mgo$find('{"Landing_Outcome": { "$regex": "^Fail", "$options": "i"}}')
print(fail)
```

```{r failed_projections}
fail_projection <- mgo$find( query = '{"Landing_Outcome": { "$regex": "^Fail", "$options": "i"}}', fields = '{"Flight_Number": true, "Landing_Outcome": true, "_id": false}')
print(fail_projection)
```